import Head from "next/head";
import Image from "next/image";
import script from "next/script";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
        {`
          h2 {
            font-size: 38px;
          }
          h2 {
            font-size: 28px;
          }
        `}
      </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={styles.mainnav}>
        <ul>
          <Link href="/">
            <a>
              <li>Home</li>
            </a>
          </Link>
          <Link href="/about">
            <a>
              <li>About</li>
            </a>
          </Link>
          <Link href="/blog">
            <a>
              <li>Blog</li>
            </a>
          </Link>
          <Link href="/contact">
            <a>
              <li>Contact</li>
            </a>
          </Link>
        </ul>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>Hunting coder</h1>
        <div className={styles.imagewrap}>
          <img
            className={styles.myImg}
            src="homeimg.avif"
            width={300}
            height={200}
          />
        </div>
        <p className={styles.description}>
          A blog for hunting coders by a hunting code
        </p>
        <div className="blogs">
          <h2>Popular blogs</h2>
          <div className="bogitem">
            <h3>How to learn javascript in 2022</h3>
            <p>Javascript is the lang. used to design logic for the web</p>
          </div>
          <div className="bogitem">
            <h3>How to learn javascript in 2022</h3>
            <p>Javascript is the lang. used to design logic for the web</p>
          </div>
          <div className="bogitem">
            <h3>How to learn javascript in 2022</h3>
            <p>Javascript is the lang. used to design logic for the web</p>
          </div>
        </div>
      </main>
    </div>
  );
}
